apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-alpha-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/pitalsmith/eks-multi-tenant-platform.git'
    targetRevision: HEAD
    path: tenants/tenant-alpha
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tenant-alpha
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-beta-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/pitalsmith/eks-multi-tenant-platform.git'
    targetRevision: HEAD
    path: tenants/tenant-beta
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tenant-beta
  syncPolicy:
    automated:
      prune: true
      selfHeal: true