apiVersion: v1
kind: Pod
metadata:
  name: network-test-pod
  namespace: tenant-alpha
spec:
  containers:
  - name: test-container
    image: curlimages/curl
    command: ["curl", "--max-time", "5", "http://backend-api-service.tenant-beta.svc.cluster.local"]
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
  restartPolicy: Never
