apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-service-deployment
  namespace: apps
  labels:
    app: sample-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-service
  template:
    metadata:
      labels:
        app: sample-service
    spec:
      containers:
        - name: app-container
          image: nginx:alpine
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: sample-service-service
  namespace: apps
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: sample-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-service-ingress
  namespace: apps
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: "app.acd0d335cbad64428bdbbcf50d59dfb4-1715155657.us-east-1.elb.amazonaws.com.nip.io"
      http:
        paths:
          - path: /demo
            pathType: Prefix
            backend:
              service:
                name: sample-service-service
                port:
                  number: 80
