apiVersion: v1
kind: Service
metadata:
  name: backend-api-service
  namespace: apps
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: backend-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-demo-ingress
  namespace: apps
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: "app.acd0d335cbad64428bdbbcf50d59dfb4-1715155657.us-east-1.elb.amazonaws.com.nip.io"
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-api-service
                port:
                  number: 80