---
apiVersion: v1
kind: Service
metadata:
  name: demo-backend-svc
  namespace: default
spec:
  ports:
    - port: 80          # External port for the service mesh
      targetPort: 8080  # The real internal port your Node.js container listens on
      protocol: TCP
  selector:
    app: demo-backend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-demo-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: demo-backend-svc
                port:
                  number: 80  # Maps to the Service port, which securely routes to 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-frontend-svc
                port:
                  number: 80